# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

format = """
[╭╴](green)$all\
[╰─](green)$character
"""

# Change the default prompt characters
[character]
success_symbol = "[>](bold green)"
error_symbol = "[<](bold red)"
